### PR TITLE
Add support for PHP 5.6 and 7.0

### PR DESCRIPTION
**Pull request by krallin**
This has inspiration coming from a variety of places, all of which are open-source
- https://github.com/tutumcloud/apache-php (variables_order)
- https://github.com/docker-library/php/blob/master/7.0/apache (the apache config file)
- https://github.com/GoogleCloudPlatform/php-docker (the php build script)

Note: the php.ini files are the production ini files from https://github.com/php/php-src

The two images use Apache as the host, considering that this is probably what most customers will expect (with `.htaccess` files, etc.).

### CODE REVIEW

**Comment by krallin** [comment]
cc @fancyremarker, @gib if you'd like to go over this

cc @wcpines, FYI.

**Comment by fancyremarker** [comment]
This is awesome! Thank you. I am in no position to intelligently review a PHP base image, but if you want me to help in testing this (and a corresponding support article) against some known PHP applications, let me know and I'm happy to help.

**Comment by krallin** [comment]
That'd be great; thanks @fancyremarker. I'm going to manually to push those images to Quay in a little bit and work on a tutorial update. Once I have that, I'd appreciate your help testing it :)

(will ping you here)

**Comment by cordoval** [comment]
would be nice if we have an nginx option too

UPDATE: php-fpm

**Comment by krallin** [comment]
@cordoval thanks for your feedback; this isn't currently on our immediate roadmap — the main reason we went with Apache here is that it's what most of our customers are using today.

That being said, if Nginx + FPM is what you want, the Google Cloud image I linked above provides exactly that (although one difference is that ours includes a patch for https://bugs.php.net/bug.php?id=71003, but it's a rather easy tweak to the image).

Cheers,

**Comment by cordoval** [comment]
one application php to test this against would be a symfony 3.1.1 app, just saying

**Comment by fancyremarker** [comment]
Merging this and will open a PR immediately after to update to latest (5.6.24 and 7.0.9).

**Comment by fancyremarker** [comment]
(Canceled build also.)

**Pull request merged**
